travis:
  secure:
    BINSTAR_TOKEN: a/rSl4Y5IsX28ZiSwlpxnY+O1X/PhLPsXH7/iVEpKBxjgz/spEY9UrRlTYI39roFIORMrr6llBizAdESDxBe2du2gQsVjiZXAudW0Dh91b3IvZ6f/aYiEpLewmSrVc1lQZcb5Qgq7tTrDG3WA9F4YoO1pQsJXesopJY8HrUXUvPYUkxVNQEAavrMe78baWuRIXinOAx9irIF2mlC+u4dfly+gDbJdo44S69nItFuku+Lgi37iUowvDIXKYHnoOSh8yWQwqFkmqpZn8AFY5/oVJkp4nC4LKQxZjMMhij/yiKU9lX2sU/215BD+msW4FGwocWbu7b7liSixgElS1l3uQOQ2MxrbQBqqDF0xWww5XpCa5H3hVqT95FO6wMM5KpeiM9by0+/UnlxyqAvz5M0jNN7S+i0Yxiucq61d/VOKYPY1s7GUc74EY7B4ueIQ1K+SVEKte0b/pxJ9/bqZVaNwWJudRNBiDhi3Vwx4EJN+/exwbmjKEmxuSDg2I0xqIPuFLF2Azhi0QSm7qpgCD/n+hnRTA+7fmYIFrAhOcaO/fheiwIk3wod3MdJoIIh/AOgCnFhmaShSde3vOr8+PwgGQD3CmUc6KtjwgW/vEjeu/YgS6E36N2wN1XAj6mQa/9xjPQm+UKHd2Waz0pEYEDi2jMByWUWiXu74tCvmzqJUAw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
